using Supabase.Postgrest.Attributes;
using Supabase.Postgrest.Models;


namespace AI_Driven_Water_Supply.Application.Models
{
    [Table("workers")]
    public class Worker : BaseModel
    {
        [PrimaryKey("id", false)] // Ensure false if ID is auto-generated by DB
        public long Id { get; set; }

        [Column("supplier_id")]
        public string SupplierId { get; set; }

        [Column("name")]
        public string Name { get; set; }

        [Column("role")]
        public string Role { get; set; }

        [Column("base_salary")]
        public decimal BaseSalary { get; set; }

        // ignoreOnInsert is correct for Postgrest-csharp
        [Column(ignoreOnInsert: true, ignoreOnUpdate: true)]
        public string TodayStatus { get; set; } = "Pending";
    }
}